import OrderNav from "@/components/Order/OrderNav";
import { Inter } from "next/font/google";

import "../globals.css";
export const metadata = {
  title: "View Order",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <header>
          <OrderNav />
        </header>
        {children}
      </body>
    </html>
  );
}
